stages:
  - build

build:docker:
  stage: build
  image: docker:18.06.3-ce
  script:
    - apk add --no-cache make git wget bash groff less python py-pip
    - pip install awscli
    - make build
  only:
    - trigger
    - master
  tags:
    - full360
