name: Alpine Images Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
    - cron: 0 0 * * 0

jobs:
  alpine:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Alpine 3.12
        uses: docker/build-push-action@v2
        with:
          context: ./alpine/3.12
          pull: true
          push: true
          tags: |
            full360/alpine:latest
            full360/alpine:3.12-alpine

  ecs:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build ECS
        uses: docker/build-push-action@v2
        with:
          context: ./ecs
          pull: true
          push: true
          tags: |
            full360/ecs:latest
            full360/ecs:1.19-alpine
            full360/ecs:1.19.1-alpine


  nomad:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Nomad 0.5
        uses: docker/build-push-action@v2
        with:
          context: ./nomad/0.5
          pull: true
          push: true
          tags: |
            full360/nomad:latest
            full360/nomad:0.5-alpine
            full360/nomad:0.5.6-alpine
